### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by WanJinpeng** [Austinlccvic/Learning-large-Q-matrix-with-Restricted-Bolzmann-Machines#1]
When generating the data of the GDINA model, can you share the code of how to generate the thetaGenerator? My coding ability is not strong, and I really encountered a problem, Thank you!

**Comment by Austinlccvic** [comment]
Hi Jinpeng,

Thanks for your interest in our paper. Please see attached the python code
for generating GDINA model data.

Best,
Chengcheng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I'm sorry to border you again. Where is the python code you mentioned to generate the data of GDINA model? I only see the CV_dina_rho25_K25.py file, this is the code to generate data for the DINA model. 
I know the difference between the two models is how to generate the thetaGenerator. So can you tell me how to generate the thetaGenerator for the GDINA model, I really need your help. Thank you！

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I'm sorry I bothered you earlier. Maybe you are busy, but I still want to thank you for your last reply. If you are not busy, I sincerely hope that you can help me sovle the last problem, because this problem has been bothering me for a long time, and I always feel that the code rewritten does not meet the requirements. If you can help me, I will be very grateful.

**Comment by Austinlccvic** [comment]
Hi,

I attached a .py file in my previous email that contains python code
generating GDINA data right? Anyway, I copied the code below again.


def QGenerator(K):#Generate Q matrix for simulation. K is the number of
latent variables, we set no of items to be 3K
    Q1=np.diag([1]*K)
    from scipy.sparse import diags
    Q2=diags([1, 1], [0,1], shape=(K, K)).toarray()
    Q3=diags([1, 1, 1], [-1, 0, 1], shape=(K, K)).toarray()
    Q=np.vstack((Q1, Q2, Q3))
    return Q

def alphaGenerator(N, K, rho):#Generate latent attributes matrix for
simulation. N is the number of people
    sigma=np.full((K,K), rho)
    sigma=sigma-rho*np.identity(K)+np.identity(K)
    z=np.random.multivariate_normal(mean=[0]*K, cov=sigma, size=N)
    threshold=np.linspace(-0.5,0.5, K)
    thresMatrix=np.outer(np.ones(N),threshold)
    alp=np.zeros((N,K))
    alp[z>thresMatrix]=1
    return alp

def thetaGenerator(Q, alpha, g, s):#Q matrix, alpha matrix, guess, slipping
    J, K = np.shape(Q)
    N=np.shape(alpha)[0]
    countAttri=np.sum(Q, axis=1)#total number of required attribute for
each item
    numSkillPosed=np.matmul(alpha, np.transpose(Q)) #N by J, count number
of skills possessed.
    thetaEff=numSkillPosed/(np.outer(np.ones(N), countAttri))
    theta=np.zeros((N, J))
    additiveProb=1-s-g
    for i in range(N):
        for j in range(J):
            if thetaEff[i,j]==1/2:
                theta[i,j]=additiveProb/3
            if thetaEff[i,j]==1/3:
                theta[i,j]=additiveProb/7
            if thetaEff[i,j]==2/3:
                theta[i,j]=3*additiveProb/7
            if thetaEff[i,j]==1:
                theta[i,j]=additiveProb
    theta=theta+np.outer(np.ones(N), np.array([g]*J))
    return theta


def gdinaGenerator(N, K, J, rho, g, s, seed):#generate acdm model data
    np.random.seed(seed)
    Q=QGenerator(K)
    alpha=alphaGenerator(N, K, rho)
    theta=thetaGenerator(Q, alpha, g, s)
    data=np.zeros((N,J))
    for i in range(N):
        for j in range(J):
            u=np.random.uniform(0, 1, 1)
            if u < theta[i,j]:
                data[i,j]=1
    return [data, alpha]

Best,
Chengcheng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I didn't see the code in the last email, I'm sorry, maybe I didn't find where it was, so I bothered you again later, thank you very much for your help. All in all, thank you sincerely for your reply. I hope you can do better in your study in the future.

Best,
Jinpeng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I'm sorry to bother you again because I have a problem. Since I want to use other real data for analysis in my academic dissertation, and I found that there are only 757 observations in your real data analysis part, did you change the 200,000 pieces of data generated by simulation into 757 pieces of real data?
Because exe function is defined to devide 200000 pieces into 100 executions, each execution of 2000 data, but the real data is not so many, my real data is only 1288 data, so the exe function can still be used? I searched on the Internet for the wrong problem how to solve, but did not get solved. Could you tell me what to do with the code that analyzes this real data. Thank you!
I will look forward to your early reply.

Best,
Jinpeng

**Comment by Austinlccvic** [comment]
Hi Jinpeng,

I think you can just change N=1288 and in the for loop in the exe function,
change "for i in range(100)" to "for i in range(1)".

Best,
Chengcheng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I also tried to do what you said before, because there was not so much data, so I changed to a loop. The result error is TypeError: 'float' object cannot be interpreted as an integer.
Since my real Q matrix is 9 by 4, so I alter this part "visible_units=9/4*K, hidden_units=K". In order for the final Q matrix to be a 9 by 4. I feel my changes are reasonable, but they still run with errors. May I ask your real data is 757? I changed it according to what you said, but it will still be wrong. I feel like I'm breaking down. May I ask how your real data code is changed?

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

Is your real number 757 subjects answering questions? What changes have you made to your code? And did you use Pycharm? If you remember, you can tell me how to deal with it, because I really need your help. 
Thank you! 

Best,
Jinpeng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

How do you estimate the Q matrix for your 757 real datas? What changes have been made to your code? Because I've changed it many times, and I also changed the batch-size to be divisible by 1288, but it still reports this error. The result error is TypeError: 'float' object cannot be interpreted as an integer.
I am a student in Northeast Normal University, because I am application-oriented, and I just want to use the method you proposed to analyze real data.That is why I have repeatedly turned to you for help. Do you have wechat? Can I add friends to consult you.

Best,
Jinpeng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I'm very sorry to disturb you again. When analyzing real data, Is the initial self.W in your fast_train.py file using the real Q matrix(which is the Q matrix specified by the expert)? Since my estimation index is not accurate enough, so I want to know where the problem is.
I'm looking forward to your early reply. Thank you!

Best,
Jinpeng

**Comment by WanJinpeng** [comment]
Hi Chengcheng,

I have a problem. The simulation results I did with Python before feel very close to the simulation in your article, (The simulation part refers to your exposed code), so I think there should be no errors in the code. However, when I did the real data of PISA, I found that the result of OE was not good, so I would like to ask you about it, because it has really troubled me for a long time. 
I prefer to be an application professional, so I only plan to use your method to make a real data and analyze the results. I tell the truth. I sincerely hope you can help me. If possible, can you tell me where the code changes when you make real data, or what the code for making real data is?
I also tried to change the code of real data many times, but the OE result was still not good. I asked my tutor, but she couldn't help me, so I couldn't help myself, so I asked for your help again. I sincerely hope you can help me, and thank you for your reply and answering me in your busy time.
Thank you!

Best,
Jinpeng
